### ISSUE TITLE
files should be gzipped

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#101]

**Comment by yrsegal** [comment]
what do I do here

**Comment by sdaitzman** [comment]
I've got it working with gulp, so I can have it auto-gzip on every build. You'll just need to send it properly, which simplehttpserver doesn't by default. See this thread: http://stackoverflow.com/questions/9622998/how-to-use-content-encoding-gzip-with-python-simplehttpserver

**Comment by yrsegal** [comment]
Implementing this guy's code verbatim as per his awesome license, https://github.com/ksmith97/GzipSimpleHTTPServer/blob/master/LICENSE

**Comment by yrsegal** [comment]
really strange errors in his code not always sending the files in full. :/

**Comment by sdaitzman** [comment]
huh, that's a weird one... no idea. also: not sure if this library does this already, but you do (probably) need to check if the receiving browser actually supports gzip. this should be in its request header, assuming I actually understand it correctly :tongue:

**Comment by yrsegal** [comment]
for reference: min.js/min.css files occasionally were truncated, and infotext.md was always truncated (up to `github.com/y`)

**Comment by sdaitzman** [comment]
How many bytes was that?

**Comment by sdaitzman** [comment]
I smell a weird HTTP quirk

**Comment by yrsegal** [comment]
um... it passed 88/106 bytes sometimes, sometimes 88 correct bytes + 17 malformed (\x00) bytes/106

**Comment by yrsegal** [comment]
so... what's up with this thing? since it doesn't seem to work right...

**Comment by sdaitzman** [comment]
I'm not sure, I haven't found any issues like that on StackOverflow. The refactors I've just done make everything fast enough that this shouldn't really be needed though. Safe to close?
