### ISSUE TITLE
Flags for only loading backend/frontend

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/LaserQueue#107]
Behavior:

If neither: load both frontend and backend
If initialize flag: load initialize and nothing else
If frontend flag: load frontend
If backend flag: load backend

We used to have this as seperate scripts, but that was clunky.

**Comment by sdaitzman** [comment]
Maybe it would be better to have a separate flag to just run initialize and quit? Telling it to run both explicitly and having it run neither would feel pretty weird to me.

**Comment by yrsegal** [comment]
closed in a4bfc9d3cd5520c838f9db05b8f3ada232726264 and afda6cad26cf58133745f4e38d74f3d126911f3f
