### ISSUE TITLE
JS compiles really, really slowly

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#108]
Upside to all JS concatenated: hella fast frontend code
Downside: 7-second compiles

Possible solution: first combine giant libraries and resources if they've been changed, into one libraries.min.js file. This will only be recompiled when a library is updated.

**Comment by sdaitzman** [comment]
This is partially fixed now, due to optimizations in gulp whereby we're no longer syntax-checking all of jquery, bootstrap, and transparency :dizzy_face:

**Comment by sdaitzman** [comment]
Doing this now in a non-ideal way. I'll have a `lib.min.js` with libraries, compiled manually with `gulp js-lib` and our code only in `scripts.min.js`. Obviously, this is not the sexiest long-term solution but I can have it done quick and it'll be a negligible difference.

**Comment by sdaitzman** [comment]
This is turning out to be interesting. I've spent a surprising amount of reading through philosophical (a)synchronous arguments on the gulp repo, but it's... close to working.

**Comment by sdaitzman** [comment]
Pushing this back to 0.0.5. @yrsegal you want to take 0.0.4 stable?

**Comment by yrsegal** [comment]
sure
