### ISSUE TITLE
{"action":"refresh"} doesn't seem to work anymore

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#110]
Ran socketSend({"action": "refresh"}) as not authed: server said I had to be authed
Ran socketSend({"action": "refresh"}) as authed: server accepted and did nothing.

**Comment by yrsegal** [comment]
config option that's off by default, not an issue.

**Comment by yrsegal** [comment]
read the api docs man

**Comment by sdaitzman** [comment]
I was editing the docs when I noticed this... I think I need more sleep.

https://duckduckgo.com/?q=facepalm&ia=images
