### ISSUE TITLE
WebSockets not working!!!

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#112]
It appears that WebSockets are not working correctly on OS X El Capitan Dev Preview 2. Instead of sending data over WebSockets, it just logs `socket.send() raised exception`.

Could you add an error handler that prints some more info when socket sending fails to help debug this?

I've tested in Chrome & Safari, so it's not browser, and I tried using the -n flag as well.

**Comment by yrsegal** [comment]
The `socket.send() raised exception.` is in 10.10 as well; and I have no control over that. It's being raised by websockets.asyncio somehow.

**Comment by sdaitzman** [comment]
Huh... so that doesn't stop things from working, then?

**Comment by yrsegal** [comment]
Nope... it's async. However, it SHOULDN'T be happening. that's the problem.

**Comment by sdaitzman** [comment]
Just out of curiosity, I switched to master branch and tested and everything is working fine there. Did you change something significant about how websockets works?

**Comment by yrsegal** [comment]
no, i made a query happen and suddenly everything borked.

**Comment by sdaitzman** [comment]
A query?

**Comment by yrsegal** [comment]
... I'm poring over websockets/asyncio's source, we'll see.

**Comment by yrsegal** [comment]
Update on this: it's happening when the websocket is CUT OFF. the first connection will always go smoothly. Close the page, wait 10 seconds, reopen: smooth.

**Comment by sdaitzman** [comment]
Huh, that's weird...

**Comment by yrsegal** [comment]
I need a way to safely cut a connection when it ends... but the question is, why did it work before...

**Comment by sdaitzman** [comment]
Any progress on this?

**Comment by yrsegal** [comment]
no, but not for lack of trying.

**Comment by sdaitzman** [comment]
Can you try reverting code until it works?

**Comment by yrsegal** [comment]
HOLY SHIT IT'S NOT ON THE BACKEND

**Comment by yrsegal** [comment]
Well... fixed but walking configs aren't happening, no way

**Comment by sdaitzman** [comment]
Wait what?

**Comment by sdaitzman** [comment]
What was the problem?

**Comment by yrsegal** [comment]
The frontend's connections weren't being initialized in a safe way, so they didn't get closed in a safe way
