### ISSUE TITLE
Weird error on Linux

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#114]
`[26/Jun/2015 21:45:02] [Setup] Error updating: 'module' object has no attribute '_create_default_https_context'`

wat does this mean @yrsegal?

**Comment by yrsegal** [comment]
replace the cprint line after the except Exception as e: with `raise e`

**Comment by yrsegal** [comment]
and give me the log

**Comment by sdaitzman** [comment]
I'm not totally sure what you mean, but here's a more full screenshot of the log:

![screenshot from 2015-06-27 09 21 50](https://cloud.githubusercontent.com/assets/1499476/8392138/02f1c558-1cae-11e5-9501-57658fc35df9.png)

**Comment by yrsegal** [comment]
Basically urllib is borked on Linux, I'll try to find a fix

**Comment by sdaitzman** [comment]
OK thanks!

**Comment by sdaitzman** [comment]
I've been testing more and it looks like everything is actually working, but... slowly. Like, 3 minute delay before actually showing any changes. I've also tested on mobile safari (different device) with the same issue.

**Comment by yrsegal** [comment]
Yep. I'm working on that too; diff issue tho.

**Comment by sdaitzman** [comment]
Is this now closed?

**Comment by yrsegal** [comment]
nope.

**Comment by sdaitzman** [comment]
Gotcha. I thought maybe it was a dupe of the issues with walkingconfig

**Comment by yrsegal** [comment]
imma do some EOS testing on this stuff
time to get sublime on that side i guess

**Comment by sdaitzman** [comment]
sounds cool!

**Comment by sdaitzman** [comment]
yay thanks! great work!
