### ISSUE TITLE
Config is not parsed

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#12]

**Comment by sdaitzman** [comment]
_config.js will now be parsing the config file instead of setting config values. This makes much more sense as it will allow a universal config file. A separate file will be used to handle private values (such as API keys if they're added in the future). This separate file will never be sent to the clientside.

**Comment by yrsegal** [comment]
config.json, the universal config file, is located in www.

**Comment by yrsegal** [comment]
Parsed, but doesn't update automatically. Leaving open until automatic updates are implemented.
