### ISSUE TITLE
Text message notifications

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#120]
Saeed and David both really, really want these

**Comment by yrsegal** [comment]
dammit david/saeed

**Comment by sdaitzman** [comment]
Sorry, but they really want them. Liam and I are willing to help however we can

**Comment by sdaitzman** [comment]
@yrsegal can you give this another try?

**Comment by yrsegal** [comment]
:( the main reason I don't want this is i don't want to implement something
like that that won't work for most people

**Comment by sdaitzman** [comment]
What if we were to implement plugins first, and then implement it as a plugin?

**Comment by yrsegal** [comment]
this is a plan I like

**Comment by yrsegal** [comment]
oooooooo

**Comment by yrsegal** [comment]
Closing since this is being continued in this: [`TextMessagePlugin`](https://github.com/LaserQueue/TextMessagePlugin)
