### ISSUE TITLE
All-new TV interface

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#121]
This is an issue to track it. This may not be actually done in 0.0.5.

**Comment by yrsegal** [comment]
why is this on our code repo

**Comment by sdaitzman** [comment]
I figure that at some point we'll probably add it to the repo so we don't need a separate set of issues and stuff for it, and I also thought you should know about any progress made on it

**Comment by yrsegal** [comment]
is this actually a thing we want?

**Comment by sdaitzman** [comment]
Nope ¯\_(ツ)_/¯

What we may want is a plugin that just hides some less necessary elements based on a config.
