### ISSUE TITLE
GO AWAY DRUNK YOU ARE ROOT (things that should not need root still need root)

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#122]
I'm unable to delete the project folder to reclone it as my user.

![screen shot 2015-07-01 at 7 43 16 pm](https://cloud.githubusercontent.com/assets/1499476/8467232/dfe019aa-2029-11e5-8dc2-cb944c00a5cb.png)

**Comment by yrsegal** [comment]
That's because you ran it as root the first time, ya derp

**Comment by yrsegal** [comment]
Python gens that stuff. Not me.

**Comment by yrsegal** [comment]
so this is basically impossible for me to fix; closing

**Comment by sdaitzman** [comment]
damn, okay
