### ISSUE TITLE
Dragging a job around sometimes results in deleting the job?

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#126]
Oddly enough, this has only appeared when using the `-l` flag. I think it's a backend thing maybe?

**Comment by yrsegal** [comment]
Requesting py log?

**Comment by sdaitzman** [comment]
Huh... this time it was not on local, but the first job I moved was deleted immediately (no weird dragging even). The rest I went pretty crazy with and nothing happened. Log: https://asciinema.org/a/5fx2yygt7p1vvcpphvo25g0he

**Comment by yrsegal** [comment]
It was a specific bug (unrelated to -l), in which any relmove moving something one below itself when one below was not the bottom would drop the item. cc85942e2a8fd7dc5405d817b0cb3823acdb3f08 fixes this.

**Comment by sdaitzman** [comment]
:+1:
