### ISSUE TITLE
Job addition access control

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#128]
@yrsegal we're likely going to start using LaserQueue on Monday-ish. Is it possible to limit the addition of jobs entirely to authenticated users? This way, we can delegate adding jobs to the interns so that they have some input with time estimates (as they will have a better sense of cut length).

Is this already a thing? Do I need to implement anything frontend?

**Comment by yrsegal** [comment]
i mean, it's possible
just edit config.json and make "add" an authaction

**Comment by yrsegal** [comment]
we can add notifications now that the server does the processing in one file, by the way

**Comment by yrsegal** [comment]
only needs to be implemented on the frontend; kill off the input box (or hide at least) if add is in authactions, and add it back if needed on auth. Remove on deauth, etc.

**Comment by yrsegal** [comment]
i'll try my hand at doing this
