### ISSUE TITLE
Dragging or using *crement buttons is broked

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#130]
The action buttons do still change, though

**Comment by sdaitzman** [comment]
@yrsegal does this work for you?

**Comment by yrsegal** [comment]
yes

**Comment by sdaitzman** [comment]
@yrsegal could you try recloning it and testing again? Because it hasn't worked in any of my VMs

**Comment by yrsegal** [comment]
not working when recloned, wtf

**Comment by yrsegal** [comment]
i know how to fix it

**Comment by yrsegal** [comment]
wtf js
so, populateactions isn't triggering when i use it in _auth.js
sam wtf did you do

**Comment by sdaitzman** [comment]
wasn't me :information_desk_person:

**Comment by sdaitzman** [comment]
I'll look into it though

**Comment by yrsegal** [comment]
im assuming it's the fault of _auth loading before _functions, but _shrugs_

**Comment by yrsegal** [comment]
the problem, by the way, is that you need to populate on auth and on deauth... which isn't happening, and I can't seem to get it to.

**Comment by sdaitzman** [comment]
It started working again, then broke again. This makes literally no sense. I'm rereading everything and maybe refactoring because WAT :confused:

**Comment by sdaitzman** [comment]
closed in daeace0 and it was super-easy :sob:

**Comment by yrsegal** [comment]
on deauth toooooooo~

**Comment by sdaitzman** [comment]
I tested ondeauth and it was fine without it in there, but I'll put it there too just in case (minimal performance downside)
