### ISSUE TITLE
Flag to set password

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#131]
There should be a flag to set the password. The user should be prompted to enter and confirm it, and their typing shouldn't show up.

**Comment by yrsegal** [comment]
the... password? explain further please

**Comment by sdaitzman** [comment]
The coach password

**Comment by yrsegal** [comment]
I don't understand what you're asking for :/

**Comment by sdaitzman** [comment]
The password to enter auth mode, the hash of the hash of which is kept in `hashpassword`

**Comment by yrsegal** [comment]
yes, but what do you want me to do :/

**Comment by sdaitzman** [comment]
Add a flag that prompts the user to set that password when they run it, to make changing the password not require editing the text file

**Comment by yrsegal** [comment]
mmkay

**Comment by sdaitzman** [comment]
It shouldn't accept a line like `$ ./start.sh --new-password superSecurePassword` since that gets saved into the user history, including the password

**Comment by yrsegal** [comment]
:( I spent half an hour reading through docs to figure out how to do that and still just do --new-password
