### ISSUE TITLE
Comment py code

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/LaserQueue#132]
it's a fucking mess

**Comment by sdaitzman** [comment]
:+1: because I've tried reading it :stuck_out_tongue:

**Comment by yrsegal** [comment]
So far, config.py and initialize.py are commented
and i'm not commenting the /scripts/html stuff, that isn't mine. That's a clone from the builtin html, with slight edits to use cprint stuff.

**Comment by sdaitzman** [comment]
sweet, thanks!

**Comment by yrsegal** [comment]
_looks at laserqueue.py_
dear god what have I gotten myself into

**Comment by yrsegal** [comment]
main.py commented

**Comment by yrsegal** [comment]
Closes upon #135 closing
