### ISSUE TITLE
Replace all applicable instances of string addition with {} formatting

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/LaserQueue#133]
{} formatting is bae

this applies to both the frontend and backend

**Comment by sdaitzman** [comment]
{} formatting? Can I have an example?

**Comment by yrsegal** [comment]
"{} is {}.".format("heyo", "what's up") -> "heyo is what's up"

"{0} {1} {0}".format("heyo", "what's up") -> "heyo what's up heyo"

**Comment by yrsegal** [comment]
I added a String.prototype.format for it a while ago in _functions.js

**Comment by sdaitzman** [comment]
What's the advantage? In some places it's prettier but for lines like this:
<img width="1314" alt="screen shot 2015-07-13 at 6 42 34 am" src="https://cloud.githubusercontent.com/assets/1499476/8647922/5f434c4a-292a-11e5-8b7d-785170b44070.png">
it'll just be more confusing, right?

**Comment by yrsegal** [comment]
trust me it looks better
logText('socketSend() has been called, but socket.readyState is {}. The socket is probably not connected yet.'.format(socketState))

**Comment by yrsegal** [comment]
3e72c10e20671560448f4514836f89b2968385a2 closes
