### ISSUE TITLE
Refactor start.py

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/LaserQueue#136]
instead of Popens and Systems, import them (`__init__.py` in scripts/) and use threading

**Comment by yrsegal** [comment]
Problem: sudo. Until I can find a way to run functions with root perms, this is impossible.

**Comment by sdaitzman** [comment]
Can I close this because Impossible?

**Comment by yrsegal** [comment]
it is actually impossible with python as is, so... yeah. (dammit apple)
