### ISSUE TITLE
Weird linux error

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#137]
<img width="1684" alt="screen shot 2015-07-14 at 10 11 31 am" src="https://cloud.githubusercontent.com/assets/1499476/8675245/c3443d62-2a10-11e5-9803-66833ae41406.png">

**Comment by yrsegal** [comment]
oh, huh
it's the same error as old... i just need to pop it in a certain place...

**Comment by yrsegal** [comment]
wait, what
I can't fix this
it's a problem in pip itself... though the second thing is fixable

**Comment by sdaitzman** [comment]
damn
also FYI this is running on master branch, not dev-0.0.5

**Comment by yrsegal** [comment]
if the bug was fixable it would have been fixed by dev-0.0.4
