### ISSUE TITLE
Backend log should contain more info on jobs acted upon

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#139]
When a job is deleted or moved, it should print what caused that but also the JSON of that job

Thoughts?

**Comment by yrsegal** [comment]
Would stuff up the log too much.

**Comment by sdaitzman** [comment]
verbose flag?

**Comment by yrsegal** [comment]
perhaps.

**Comment by sdaitzman** [comment]
Alternatively, could print what's actually happening (<Name> removed from queue) and have a verbose flag that prints that and also the JSON received

**Comment by yrsegal** [comment]
the log will stay how it is, and the verbose flag will add "removed", etc

**Comment by sdaitzman** [comment]
ok cool

**Comment by yrsegal** [comment]
213385bc4422a0f84c17b131a13e209ce2a47da4 closes.
