### ISSUE TITLE
error: name 'authstate' is not defined when trying to remove a job

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#145]
<img width="615" alt="screen shot 2015-07-21 at 8 38 34 pm" src="https://cloud.githubusercontent.com/assets/1499476/8815539/87811aa6-2fe8-11e5-8f76-06e90d9dae6a.png">
<img width="1165" alt="screen shot 2015-07-21 at 8 39 20 pm" src="https://cloud.githubusercontent.com/assets/1499476/8815549/98fd9c64-2fe8-11e5-8652-4fbccf31bf35.png">
They did get deleted, but it displayed a modal and errored

**Comment by yrsegal** [comment]
ffff ok, easy fix
