### ISSUE TITLE
refactor bcolors to use curses

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/LaserQueue#147]
with curses, I can color things on windows

**Comment by sdaitzman** [comment]
![tumblr_ml2ci92zf11rit6p2o3_250](https://cloud.githubusercontent.com/assets/1499476/8928532/1817221e-34ed-11e5-911c-2b340a8b04bd.gif)

**Comment by yrsegal** [comment]
eeeeeeh this would be a lot harder than it seems
windows users won't get all these codes without ansicon, I guess
