### ISSUE TITLE
metabump appears to not be working

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#150]
@yrsegal can you reproduce this?

**Comment by sdaitzman** [comment]
The labels are broken. Should be !!! Bug

**Comment by yrsegal** [comment]
Explain what you mean by labels being broken

**Comment by sdaitzman** [comment]
Oh, that's just a bug in github :sob: unrelated to the issue. The issue is that I can't get metabump to work at all

**Comment by yrsegal** [comment]
Ok, I'll take a look.

**Comment by sdaitzman** [comment]
thanks!

**Comment by sdaitzman** [comment]
Interestingly, 492af4cf5c543d44b87d12cf89c280f5041b22f8 makes it work again.... but backwards. It slowly lowers job priority down to lunch / after nuvu

**Comment by yrsegal** [comment]
huh...

**Comment by sdaitzman** [comment]
Instead of raising the lower-level jobs up over time, it lowers all jobs over time

**Comment by sdaitzman** [comment]
I totally recloned to test it and it's still happening that way

**Comment by yrsegal** [comment]
fixed for sure, i had looked over the -1 case for metabumpmax
