### ISSUE TITLE
Frontend plugin support

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#151]
Prerequisite on frontend: refactor _a lot_

**Comment by sdaitzman** [comment]
@yrsegal can you fix the labels on this one too? Should be `!!` `Missing feature`

**Comment by yrsegal** [comment]
also requisite on Frontend: make a mutable Object that the socket uses to parse incoming, kinda like I have on the backend
as in:

```
  {
    "display": displayFunc,
    "notification": notificationFunc,
    "refresh": refreshFunc,
    "rickroll": rickroll
  }
```

and so on.

functions should accept an Object, which they then pull items out of. This allows for future expandability. The data, as it is now, should simply be: 

```
  {
    "data": jsonData
  }
```

**Comment by sdaitzman** [comment]
why? (I see lots of good reasons to do this but I'm not sure why it's a requirement for this)

**Comment by yrsegal** [comment]
so others can add their own commands, corresponding to their own commands on the backend.

**Comment by sdaitzman** [comment]
oh damn

**Comment by yrsegal** [comment]
clearing assignee since we both have things to do

**Comment by sdaitzman** [comment]
@github <cough> _multiple asignees_ </cough>

**Comment by yrsegal** [comment]
so how will i do JS parsing? right now it just concats + dumps in a file.

**Comment by sdaitzman** [comment]
that's probably enough! where does it put the file?

**Comment by yrsegal** [comment]
www/dist/plugins.js

**Comment by sdaitzman** [comment]
can it create that whether there are plugins are not?

**Comment by yrsegal** [comment]
it already does. Committed that a few seconds ago.

**Comment by sdaitzman** [comment]
nice

**Comment by sdaitzman** [comment]
plugins are now on the frontend! now, to make that be actually helpful

**Comment by yrsegal** [comment]
woo

**Comment by yrsegal** [comment]
relevant: https://github.com/LaserQueue/LaserQueue/commit/0c5d5588d171c04b68df276d057e85d33a6209f7

**Comment by sdaitzman** [comment]
they can just name an uncompressed file foo.min.js though

**Comment by yrsegal** [comment]
yeah
but that would be mean
and this is to prevent the js they're working on to be concatenated, as opposed to the final js

**Comment by sdaitzman** [comment]
ok that makes sense

**Comment by yrsegal** [comment]
so, how goes the port to an `Object socketCommands`?

**Comment by yrsegal** [comment]
Just noticed this is 151
...
*restrains self*
*breaks free*
_whispers "gotta catch em all"_

**Comment by yrsegal** [comment]
this works \o/
