### ISSUE TITLE
Python doesn't clean up threads

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/LaserQueue#154]

**Comment by yrsegal** [comment]
_screams internally at sudo_

**Comment by yrsegal** [comment]
_cries at sh_

**Comment by yrsegal** [comment]
god
dammit
sudo

@sdaitzman you know more about the internals than i do, we need to talk about how im going to fix this

**Comment by sdaitzman** [comment]
I haven't actually looked much at your thread creation code, I'll take a look today if I get a chance

**Comment by yrsegal** [comment]
That's not the problem, I'll need to actually talk this out

**Comment by yrsegal** [comment]
_cries further_

**Comment by yrsegal** [comment]
@sdaitzman teach me to chown to a non-root user and i'll do the things

**Comment by sdaitzman** [comment]
I'm actually not really sure

**Comment by yrsegal** [comment]
oh no

**Comment by sdaitzman** [comment]
`man chown`

**Comment by yrsegal** [comment]
`--reference=RFILE`
seems like I have a plan... os.path.expanduser("~") as rfile?

**Comment by yrsegal** [comment]
```
os.environ.get('SUDO_UID')
os.environ.get('SUDO_GID')
```

oh

**Comment by yrsegal** [comment]
![b4rvc4icqaar65m jpg-large](https://cloud.githubusercontent.com/assets/6596492/9217579/09662d28-40d2-11e5-992b-4662d5366f3b.jpg)

**Comment by yrsegal** [comment]
aaaaarg this is too complex an issue

**Comment by sdaitzman** [comment]
@yrsegal safe to push back to 0.0.7?

**Comment by yrsegal** [comment]
yeah this is fucking annoying to do :/ _hates threading_
screw it, sudo calling behavior is getting changed in 0.0.7

**Comment by yrsegal** [comment]
FFFFFFF
FFFFFFFFFFFFF
"F"*1000

**Comment by yrsegal** [comment]
_**IT IS DONE**_
