### ISSUE TITLE
Update fails without internet (good). Update spews errors without internet (bad)

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#155]
https://asciinema.org/a/4p4ingp6a110vuikxswzpjit6

**Comment by yrsegal** [comment]
I've looked into it before but decided it wasn't worth the effort, I'll try
to find a way to fix it

**Comment by sdaitzman** [comment]
Can't Python handle errors somehow? There has to be some builtin or something for that

**Comment by yrsegal** [comment]
I can, and i already do, but the problem is it's hard to actually tell if
that error should be dumped or not.

**Comment by sdaitzman** [comment]
Can you watch for that error code?

**Comment by yrsegal** [comment]
its thrown by an invalid target as well, though...
