### ISSUE TITLE
No standard way for plugins to add job attributes

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#156]
Like phone number, etc.

The form will have an associated object with things to ask the user for, which can be modified by a plugin and when they render the form again the changes will be reflected.

Thoughts on this for backend?

**Comment by yrsegal** [comment]
as it is now, you have to define your own command to set the attribute. I'll see what i can do towards the backend side of this.

**Comment by yrsegal** [comment]
do your frontendy things

**Comment by sdaitzman** [comment]
Trying this again today

**Comment by sdaitzman** [comment]
Committed in 7d4de0c 3cc53d9 f99c825

Works:
- name field
- time field
- material dropdown
- priority dropdown

Broked and TODO:
- headers for selects
- refactor to integrate form render
- ~~rendering form adds new form elements~~

Related things for another issue:
- IDs are used instead of classes
- (maybe) switch to native non-jquery element creation because Performance

**Comment by yrsegal** [comment]
use le transparency for the render, man

**Comment by sdaitzman** [comment]
I tried that way

*shudders* I survived

**Comment by sdaitzman** [comment]
I'll refactor and it should be as fast. The code is ugly right now but I'll work on that too

**Comment by sdaitzman** [comment]
OK this may actually need to be transparency :/

**Comment by sdaitzman** [comment]
Closing this issue and opening two related ones (#164 and #165)

Transparency will not be needed, but it's likely better to have it than not.
