### ISSUE TITLE
Can't have multiple function handlers for one backend to frontend API call

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#157]

**Comment by yrsegal** [comment]
hurm. I can probably do this.

**Comment by yrsegal** [comment]
done

**Comment by sdaitzman** [comment]
wait really? on which branch? (I can't see it)

EDIT: never mind it showed up

**Comment by yrsegal** [comment]
dev-0.0.5 (it's a small change tbh)
https://github.com/LaserQueue/LaserQueue/commit/759b903c76a4154242ec488dfb17946e9de2efbe, then https://github.com/LaserQueue/LaserQueue/commit/81aa5128b1f3848d13b5f66d09b2c2c0dda8c02a fixes a bug with it
