### ISSUE TITLE
SHA256 is not secure enough for passwords

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#158]

**Comment by yrsegal** [comment]
what is

**Comment by sdaitzman** [comment]
It's enough for transit, but the second layer should be something more like bcrypt or scrypt

**Comment by sdaitzman** [comment]
Closing this because on more research, it is good enough

**Comment by yrsegal** [comment]
this is why i chose it, sam... >.<
i switched from sha1 forever ago since that's NOT secure
