### ISSUE TITLE
formatUnicorn is only implemented in JS

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/LaserQueue#162]
won't be too hard

**Comment by yrsegal** [comment]
thiiis will take a while

**Comment by sdaitzman** [comment]
can I move this to 0.0.6?

**Comment by yrsegal** [comment]
no

**Comment by sdaitzman** [comment]
is the idea to have formatUnicorn on the backend as well?

**Comment by yrsegal** [comment]
yes

**Comment by sdaitzman** [comment]
sweet :+1:

**Comment by yrsegal** [comment]
goddamn it python
reassigning str does nothing, and you can't redefine properties of str
>.<
why do you not have prototypical systems, and why would using pip's `prototype` take a total refactor

`44 matches across 7 files`
_cries_

**Comment by yrsegal** [comment]
https://github.com/LaserQueue/LaserQueue/commit/9573913154dc02373bfdd7670339094b9a67eee9

**Comment by yrsegal** [comment]
closed with https://github.com/LaserQueue/LaserQueue/commit/e0456ca5286aac462f98e11439bfa423980de1f5
