### ISSUE TITLE
Config is a mess of evil

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/LaserQueue#167]
Make config.md, then i'll redo all the things I can

**Comment by yrsegal** [comment]
that's
not what i meant >.<
I mean actually MAKE THE CONTENT OF IT

**Comment by sdaitzman** [comment]
Oh I know, I just haven’t done the content yet :P

**Comment by yrsegal** [comment]
dooooo eeeet

**Comment by sdaitzman** [comment]
002f52a automatically generates config.md

**Comment by yrsegal** [comment]
fiiinish it

**Comment by sdaitzman** [comment]
Anything else to do for this issue?

**Comment by yrsegal** [comment]
i have things to do for this issue

**Comment by sdaitzman** [comment]
ok cool
