### ISSUE TITLE
Refactor renderForm

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/LaserQueue#168]
shia.gif

**Comment by sdaitzman** [comment]
27bb9bc should help
and f6fdc28 means not rendering the form when it's silly to do so

**Comment by yrsegal** [comment]
this is the last thing in 0.0.5 man

**Comment by sdaitzman** [comment]
what else needs doing for this?

**Comment by sdaitzman** [comment]
(I'm not sure what's left to refactor)

**Comment by sdaitzman** [comment]
Closing this because (I think) it's done
