### ISSUE TITLE
No version printed

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#175]
The software should print its version when it starts (at least in verbose mode).

**Comment by sdaitzman** [comment]
d370554 prints it on the frontend

**Comment by sdaitzman** [comment]
@yrsegal your commit fixes this, right?

**Comment by yrsegal** [comment]
ok now this is done as of 6cb109f86c8d90f1b66e706349a1dc72d4c2d04e

**Comment by yrsegal** [comment]
sam
sam it's bold
look how beautiful it is
