### ISSUE TITLE
0.0.5 spews errors every few minutes at NuVu

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#179]
Any ideas @yrsegal ?

Aside from the spewing of weird errors, everything is working.

![laserqueue error log](https://cloud.githubusercontent.com/assets/1499476/9968566/2681ee12-5e17-11e5-809d-53ddb62643fa.png)
`Fatal read error on socket transport
protocol: <websockets.server.WebSocketServerProtocol object at 0x1094bf0b8>
transport: <_SelectorSocketTransport fd=9 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/selector_events.py", line 662, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 60] Operation timed out
Fatal read error on socket transport
protocol: <websockets.server.WebSocketServerProtocol object at 0x1094f1b38>
transport: <_SelectorSocketTransport fd=11 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/selector_events.py", line 662, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 60] Operation timed out`

**Comment by yrsegal** [comment]
what in hell

**Comment by sdaitzman** [comment]
hell
in
hell

**Comment by yrsegal** [comment]
Not a single fucking clue what this is

**Comment by sdaitzman** [comment]
it doesn't seem to be causing any issues... can you catch the error or something?

**Comment by yrsegal** [comment]
if i could, it would already be caught...

**Comment by yrsegal** [comment]
this is apparently a problem with the situation, and therefore unfixable? It's a problem with the wifi, so yell at david

**Comment by yrsegal** [comment]
closing as it's impossible to fix
