### ISSUE TITLE
Constant ValueErrors on 0.0.6

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#180]
@yrsegal try adding like 5 jobs to the queue on 0.0.6 and then deleting them all. I've got a 3,000-line log of this issue happening repeatedly today :sob:

**Comment by yrsegal** [comment]
appears to be a frontend issue, you're sending the wrong uuid back?

**Comment by sdaitzman** [comment]
Confirmed that it's a frontend issue, and not a bug in Bootstrap 4. Still not sure what it is, though...

**Comment by sdaitzman** [comment]
Closing this because it's the same as #181
