### ISSUE TITLE
Plugins are "not a plugin"

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#183]
Should print what makes them not a plugin at least
<img width="706" alt="screen shot 2015-10-07 at 11 18 48 am" src="https://cloud.githubusercontent.com/assets/1499476/10342594/be517986-6ce7-11e5-94b0-d018a7eec45f.png">

**Comment by yrsegal** [comment]
Are there any Python files in the top level of the plugin directory?

**Comment by sdaitzman** [comment]
_reads documentation_
_facepalm_
sorry
