### ISSUE TITLE
Custom events

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#187]
Things like auth and deauth should be events, not functions. This way plugins can write event handlers better.

(likely not 0.0.7)

**Comment by yrsegal** [comment]
as well as an eventRegistry in the python too

**Comment by yrsegal** [comment]
sam
just
do it

**Comment by yrsegal** [comment]
Todo on this: 

use the js `registry` for all plugin registration stuff.

**Comment by yrsegal** [comment]
is this done

**Comment by sdaitzman** [comment]
I'm trying to port some existing functions to events, but that can come later (no significant gain except it makes the code pretty :stuck_out_tongue_closed_eyes: )
