### ISSUE TITLE
unify variable name scheme

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/LaserQueue#191]

**Comment by yrsegal** [comment]
this is so important that I have made a new label to impress upon us how important this is

**Comment by sdaitzman** [comment]
Agreed. What do you want to standardize on?

**Comment by yrsegal** [comment]
Probably snake

**Comment by sdaitzman** [comment]
You sure? I'd do snake_case for backend and JSON and camelCase for JS

**Comment by sdaitzman** [comment]
strong JS convention

**Comment by yrsegal** [comment]
mmmmmmmmph, but I want unification

**Comment by sdaitzman** [comment]
But both python and JS have strong naming conventions that we don’t wanna break

**Comment by yrsegal** [comment]
Python's case standard is all lowercase, not underscores

**Comment by yrsegal** [comment]
Config/JS/registries will be camel
Python will be underscores

**Comment by yrsegal** [comment]
on another note, configs will probably become rather invalid

**Comment by sdaitzman** [comment]
What do you mean configs will be invalid?

**Comment by yrsegal** [comment]
I'll be unifying config cases as well

**Comment by yrsegal** [comment]
is this done? I want you to look over it first, sam

**Comment by sdaitzman** [comment]
I have work for a few final projects about to be due so it might be a couple days

**Comment by yrsegal** [comment]
ok

**Comment by yrsegal** [comment]
so is this done

**Comment by sdaitzman** [comment]
After CodeDay I want to do a full feature test so we catch anything like this

**Comment by sdaitzman** [comment]
All features look good; documentation doesn't :stuck_out_tongue_closed_eyes:

**Comment by sdaitzman** [comment]
Can you use your magic regex on the docs?

**Comment by yrsegal** [comment]
which docs?

**Comment by sdaitzman** [comment]
`API.md` has references to `admin_mode_enabled`

**Comment by sdaitzman** [comment]
I haven't looked at any other documentation yet

**Comment by yrsegal** [comment]
Ah, got it

**Comment by sdaitzman** [comment]
Closing (let me know if there are any other lingering underscores)
