### ISSUE TITLE
Better input parsing to stop XSS attacks and errors

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#193]
oops
![screen shot 2015-11-10 at 10 14 21 am](https://cloud.githubusercontent.com/assets/1499476/11069454/31951a34-87a4-11e5-8c03-70c91f1bf9a6.png)
Both the backend and frontend should have stopped this.

**Comment by yrsegal** [comment]
That shouldn't resolve to html though

**Comment by sdaitzman** [comment]
Closing this because I don't think it actually caused the issue at NuVu, and we have pretty solid XSS prevention on frontend.
