### ISSUE TITLE
Print out config on start

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#24]

**Comment by sdaitzman** [comment]
fixed by https://github.com/yrsegal/LaserQueue/commit/76e83e4023c12f577e95fc8ddccaf6859e940871

**Comment by shannahs** [comment]
hello ,grbl did not work...have any help for me..

**Comment by yrsegal** [comment]
Could you please explain your problem in a new issue, and not just by saying "it didn't work"?

**Comment by sdaitzman** [comment]
Do you mean grbl as in https://github.com/grbl/grbl, the grbl CNC firmware?
