### ISSUE TITLE
Warning popovers for deletion, passing etc.

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#26]
Popovers should warn the user before they delete a job.

**Comment by yrsegal** [comment]
last thiiiiiiiiiiing till 0.0.4 (viridis, means 'blooming', as a reference to all the style changes)

**Comment by sdaitzman** [comment]
My brother is working on it, he doesn't want me to do it. @jdtzmn any progresss?

**Comment by jdtzmn** [comment]
I am done with it!

**Comment by sdaitzman** [comment]
@yrsegal code should be pushed soon! Just needs a minor patch to hide the tooltips; that's nearly done. I can't test, as both Python and virtualizing Linux are pretty broken on 10.11. Considering downgrading just because of that. For now, let's focus on getting this release out soon! NuVu summer starts a week from Monday and I'd like to have the latest version running then.
