### ISSUE TITLE
Add clock to corner

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/LaserQueue#33]
Display time in corner, so you can glance at the tv screen and get the time

referencing #3, this should be the furthest to the corner, closer than the two clocks for those

**Comment by sdaitzman** [comment]
On Friday Liam and I did a redesign just for the TV and Saeed really liked it, so we should consider basing the TV interface more on that. I'll show you on Monday!

**Comment by sdaitzman** [comment]
Closing this because I don't think it's relevant (aside from the TV interface #121)
