### ISSUE TITLE
Setup sucks

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#4]
There should be a script (or at least instructions) to initialize the system. Ideally there should be one file to start that handles everything (including the webserver and backend). There should also be a way to start just the frontend (for use with a different webserver or computer) or just the backend.

**Comment by yrsegal** [comment]
dropping priority because mostly resolved

**Comment by sdaitzman** [comment]
Mostly fixed, so moving to 0.1.0 milestone.
