### ISSUE TITLE
Session IDs and timeout

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/LaserQueue#50]
will be cached with -b
if your sid is too old, it will be invalid and not respond to commands.
auth can give an sid admin, which will be required for all admin commands. 
all packets to server will have an tag "sid", which is their sid. This will only be applicable to admin commands for now.
your sid will be generated on page load. it'll be a uuid.

Related to #42

**Comment by sdaitzman** [comment]
Should this be 0.0.4 or 0.1.0? It's a significant change that will not be backwards-compatible, if I understand correctly.

**Comment by sdaitzman** [comment]
UUIDs for frontend: https://broofa.github.io/node-uuid/docs/uuid.html

**Comment by yrsegal** [comment]
you need to do frontend implementation of sids (without them the frontend no longer works)

**Comment by sdaitzman** [comment]
Which branch should I implement on?

**Comment by yrsegal** [comment]
0.0.3

**Comment by sdaitzman** [comment]
Started trying to implement, but I'm having issues on your end (I think). Will show you tomorrow.
