### ISSUE TITLE
Sha1 hashing of pass on frontend

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/LaserQueue#59]

**Comment by sdaitzman** [comment]
Syntax:
`
  {
      "action":"auth",
      "args":[hash],
      "sid": SID
  }
`

**Comment by sdaitzman** [comment]
fixed in https://github.com/yrsegal/LaserQueue/commit/2aacec37ffb02bb92c9d39d897ca8cf956e2b16a but still needs GUI to fix related issue #9
