### ISSUE TITLE
Plugins!

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#76]
PLUGINS!!! Abilities:
- address list easily
- modify frontend code (will require frontend code to be manipulatable from backend
- add custom js to frontend
- add self to config file, or have a plugin config file, etc.
- update automatically (git pull)
- other stuff
- should use a standard structure

**Comment by yrsegal** [comment]
a2cfab29b86637c7bc2258eba6361b7503524c1b will be useful for plugins

**Comment by yrsegal** [comment]
plugins are becoming more and more possible... >:D (Specifically with socket commands being `**kwargs`) implemented, and a list being used for commands. 
Queue commands must become relative before this is possible; thankfully `**kwargs` allows that with no hassle.
Plugins would (at least on the py side) have these:

`upkeep` (`function`)
run through the upkeep thread, every `config.refreshRate` seconds.

`socketCommands` (`list`)
a set of `jsonhandler.SocketCommand` (plugins will have to `import ActionFramework`, which will be added to their `sys.path` using python magic i'll pull from MCEdit. This will supply the `socketCommand` object.)

that's all, for now.

**Comment by sdaitzman** [comment]
sweet :smile:

**Comment by yrsegal** [comment]
https://github.com/mcedit/mcedit/blob/master/editortools/filter.py
putting this here since i'm using codewarrior's sweet dyn-load code to implement plugins

**Comment by yrsegal** [comment]
Plugins now work on `plugins` branch, but only on the python side. we'd need a way to inject code into the js. However, i'm merging in plugins.

**Comment by yrsegal** [comment]
why was this not closed
