### ISSUE TITLE
Action buttons should probably be a transparency directive

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#78]
@yrsegal

**Comment by sdaitzman** [comment]
@yrsegal

**Comment by yrsegal** [comment]
dammit already doing it

**Comment by yrsegal** [comment]
sort of kinda did it
kinda

**Comment by sdaitzman** [comment]
closed in https://github.com/yrsegal/LaserQueue/commit/770c7b2fda41232ccda5f8173705f0280deffaa0
