### ISSUE TITLE
Add attr implemententasnition on the frontenf

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#86]
Should make it simple to  send:

```
  {
    "action":"attr",
    "args": [uuid of job, attribute name (in json object), new value]
  }
```

**Comment by sdaitzman** [comment]
What do I actually do?

**Comment by yrsegal** [comment]
you send 
{
  "action":"attr",
  "args": [uuid of job, attribute name (in json object), new value]
}

**Comment by sdaitzman** [comment]
wat

![screen shot 2015-06-18 at 7 52 34 am](https://cloud.githubusercontent.com/assets/1499476/8230526/0661bad4-158f-11e5-8da0-f7be0ba0511b.png)
![screen shot 2015-06-18 at 7 53 01 am](https://cloud.githubusercontent.com/assets/1499476/8230529/185f8fb8-158f-11e5-9a97-c81dbbd75601.png)

**Comment by yrsegal** [comment]
that error was fixed

**Comment by sdaitzman** [comment]
mostly closed in https://github.com/yrsegal/LaserQueue/commit/71cd1c3775b79b2d0282fc15d32fe4e65a07ed75 totally closed in https://github.com/yrsegal/LaserQueue/commit/34ce046ae0c592582827be321d6f6166b491f82d

**Comment by yrsegal** [comment]
was never actually implemented, just set up ಠ_ಠ

**Comment by sdaitzman** [comment]
how should it be implemented? I thought setting it up was the implementation

**Comment by yrsegal** [comment]
No, making it a button or similar (so anyone can use it) would be better

Disable all uses that need admin, etc

**Comment by sdaitzman** [comment]
Do we really want users to be able to change that kind of thing? I can't think of a situation where it would be better than having some specialized interface

**Comment by yrsegal** [comment]
Right. Push this to 0.1.0 (I'm on mobile rn), until we make job claiming.
