### ISSUE TITLE
In coach mode, jobs should be draggable

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#87]
Using  http://draggabilly.desandro.com/ or something similar.

**Comment by sdaitzman** [comment]
@yrsegal I think I can implement this, I just need an API that lets an authed user pass the new location as an index (like, out of the entire list).

**Comment by yrsegal** [comment]
ok, similar to pass...

**Comment by sdaitzman** [comment]
pass just lowers by one, correct?

**Comment by yrsegal** [comment]
Yes, but I was talking about the theory.

**Comment by sdaitzman** [comment]
oh yeah definitely!

**Comment by yrsegal** [comment]
your command is implemented as of d76064a9efe6617cb05beda593d057d0428ed4fc

```
  {
    "action": "relmove",
    "args": [uuid, target index in the master index]
  }
```

**Comment by sdaitzman** [comment]
How I'm planning to do things at first: only works in coachmode, and you can move the job anywhere in the list

How I'm planning to do things later/in an ideal world: same, but you can drag your own job _down only_ and once you release it's moved

**Comment by yrsegal** [comment]
drag your own job down, once we do logins? I like. (after you do this i'll be changing the way action directives work, by the way.)

**Comment by sdaitzman** [comment]
Fixed in https://github.com/yrsegal/LaserQueue/commit/5ba24a69b83465a6166c9d3d0442d5e467f2cae8 :smiley:
