### ISSUE TITLE
Coach mode needs implementing

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/LaserQueue#9]

**Comment by sdaitzman** [comment]
This isn't strictly needed, so we're pushing it back to 0.1.0

**Comment by yrsegal** [comment]
@sdaitzman 
{
  "action":"auth",
  "args":[sha1 hash of password],
  "sid": SID
}

check the returned auths:[] if the first half of SID is in. if so, then continue. Else, if in deauths:[], then display the message and send

{
  "action":"shame",
  "sid": SID
}

**Comment by yrsegal** [comment]
effing finally, closed
