### ISSUE TITLE
Dragging item should have a quick preview

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#93]
When dragging an item through the list, the other items should move out of the way to show where it will end up.

**Comment by sdaitzman** [comment]
Closing as a dupe of #99 which provides more relevant info

![Taylor swift waving goodbye](http://media.tumblr.com/f6437c5e83239e1413db85b72488a4f1/tumblr_inline_mjxm4pA5aG1qz4rgp.gif)

**Comment by yrsegal** [comment]
dammit sam
