### ISSUE TITLE
Logo scale changes weirdly on mobile

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#94]
Gets super-giant on my phone, gets super-tiny on iOS Simulator.

**Comment by yrsegal** [comment]
same thing on safari in general

**Comment by sdaitzman** [comment]
I think this is just a weird safari SVG bug... unfortunately there are a lot of those :/

**Comment by sdaitzman** [comment]
Closing because I've done lots of research and this doesn't seem really fixable and ugh mobile safari why do you do this to me
