### ISSUE TITLE
gulp doesn't end after all jobs are done

### ISSUE THREAD

**Issue by yrsegal** [yrsegal/LaserQueue#97]
you have to ctrl+c it

**Comment by sdaitzman** [comment]
that's... not a bug

`$ gulp sass` compiles sass
`$ gulp js` compiles js
`$ gulp js-watch` compiles js and watches for changes to run again
`$ gulp sass-watch` compiles sass and watches for changes to run again
`$ gulp` runs `js-watch` and `sass-watch`

**Comment by yrsegal** [comment]
ohhhhhh ok
