### ISSUE TITLE
_config.js and especially _functions.js are hellspawn and should be split into multiple files

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#98]

**Comment by sdaitzman** [comment]
_config.js kinda makes sense, _functions.js has a _lot_ of code that should be in separate js files

**Comment by sdaitzman** [comment]
I'll just comment out `_functions.js`, since it's massive but on second look actually styled pretty well. 

_config.js on the other hand... needs work. A very significant part of it is not actually to do with config and should in fact be in _init.js.

Doing now, where now is probably tomorrow

**Comment by yrsegal** [comment]
you could rename it `_applyConfig.js`. It makes the significant part more reasonable.
