### ISSUE TITLE
When dragging items in table, blank space should appear under the item

### ISSUE THREAD

**Issue by sdaitzman** [yrsegal/LaserQueue#99]
1. ![Taylor Swift](http://images5.fanpop.com/image/photos/31400000/taylor-taylor-swift-31491615-1920-1200.jpg)
2. Stated blank space should follow under the item being dragged, making it clear where it'll... well, write your name.

**Comment by yrsegal** [comment]
Goddamnit

**Comment by sdaitzman** [comment]
This is proving much more difficult than expected so I'm pushing it back to 0.1.0. Issue #100 is a prerequisite.

**Comment by sdaitzman** [comment]
Closing because people don't actually seem to want this
